import type { Metadata } from "next";
import "./globals.css";
import { calibre, pretendard } from "@/styles/fonts";
import GNB from "@/components/GNB";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${calibre.variable} ${pretendard.variable}`}>
        <GNB />
        {children}
      </body>
    </html>
  );
}
